routes/web.php
<?php
//use Illuminate\Support\Facades\Route;
//use App\Http\Controllers\HomeController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Admin
Route::post('admin/login','UserController@loginAdmin')->name('admin.login');
Route::view('admin/login','admin.pages.login')->name('login.admin');
Route::get('/logoutAdmin','UserController@logoutAdmin')->name('logoutAdmin');

Route::get('getproducttype','AjaxController@getProductType');
Route::group(['prefix' => 'admin', 'middleware' => 'adminMiddleware'],function(){
    Route::resource('dashboard','DashboardController');
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('category','CategoryController');
    Route::resource('producttype','ProductTypeController');
    Route::resource('product','ProductController');
    Route::resource('order','OrderController');
    Route::resource('warranty','WarrantyController');

    Route::get('getlist','UserController@getList')->name('user.getList');

    Route::get('deleteUser/{id}','UserController@destroy')->name('user.delete');

    Route::get('createUser','UserController@create')->name('user.create');

    Route::post('addUser','UserController@store')->name('user.add');

    Route::get('editUser/{id}','UserController@edit')->name('user.edit');

    Route::post('updateUser','UserController@update')->name('user.update');

    Route::get('updateWar/{id}','WarrantyController@update')->name('warranty.update');

    Route::get('completeWar/{id}','WarrantyController@complete')->name('warranty.complete');

    Route::get('cancelWar/{id}','WarrantyController@cancel')->name('warranty.cancel');

    Route::post('updatePro/{id}','ProductController@update');

    Route::get('cancle/{id}','OrderController@cancle')->name('order.cancle');

    Route::get('check/{id}','OrderController@check')->name('order.check');

    Route::get('complete/{id}','OrderController@complete')->name('order.complete');
});

//Client
Route::post('login','UserController@loginClient')->name('login');
Route::get('/logout','UserController@logout')->name('logout');
Route::post('register','UserController@registerClient')->name('register');
Route::get('/myorder','UserController@index')->name('myorder');
Route::get('/myorder/show/{id}','UserController@show')->name('myorder.show');
Route::get('/myorder/warranty/{id}','WarrantyController@create')->name('myorder.warranty');
Route::post('/myorder/warranty/send','WarrantyController@store')->name('warranty.send');

Route::get('/','HomeController@index')->name('home-page');
Route::get('trangchu.html','HomeController@index');
Route::resource('cart','CartController');
Route::get('addcart/{id}','CartController@addCart')->name('addCart');

Route::view('checkout','client.pages.checkout');
Route::get('checkout','CartController@checkout')->name('cart.checkout');
Route::resource('customer','CustomerController');
Route::get('/{slug}.html', 'HomeController@getDetail')->name('product-detail');

Route::post('searchname','ProductController@searchName')->name('search.name');
Route::post('searchtype','ProductController@searchType')->name('search.type');

Route::get('/warranty-period/{order_id}/{product_id}', 'WarrantyController@getPeriod');

Route::get('/danh-muc/{slug}/{id}', 'HomeController@getProductByCategory')->name('product.get-by-category');
Route::get('/danh-muc-loai/{slug}/{id}', 'HomeController@getProductByProductTypes')->name('producttype.get-by-category');

app/Http/Controllers/ProductTypeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\ProductTypes;
use App\Models\Categories;
use App\Http\Requests\StoreProductTypeRequest;
use Validator;

class ProductTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $producttype = ProductTypes::paginate(10);
        return view('admin.pages.producttype.list',compact('producttype'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = Categories::where('status',1)->get();
        return view('admin.pages.producttype.add',compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreProductTypeRequest $request)
    {
        $data = $request->all();
        $data['slug'] = utf8tourl($request->name);
        if(ProductTypes::create($data)){
            return redirect()->route('producttype.index')->with('thongbao','Đã thêm thành công loại sản phẩm');
        } else {
            return back()->with('thongbao','Có lỗi xảy ra xin kiểm tra lại');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  $id
     * @return \Illuminate\Http\Response
     */
    public function show(ProductType $productType)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \$id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $producttype = ProductTypes::find($id);
        $category = Categories::where('status',1)->get();
        return response()->json(['category' => $category, 'producttype' => $producttype],200);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(),
            [
                'name' => 'required|min:2|max:255',
            ],
            [
                'name.required' => 'Tên loại sản phẩm không được bỏ trống',
                'name.min' => 'Tên loại sản phẩm tối thiểu có 2 ký tự',
                'name.max' => 'Tên loại sản phẩm tối đa có 255 ký tự',
            ]
        );
        if($validator->fails()){
            return response()->json(['error' => 'true', 'message' => $validator->errors()],200);
        }
        $producttype = ProductTypes::find($id);
        $data = $request->all();
        $data['slug'] = utf8tourl($request->name);
        if($producttype->update($data)){
            return response()->json(['result' => 'Đã sửa thành công loại sản phẩm có id '.$id],200);
        }else{
            return response()->json(['result' => 'Đã sửa không thành công loại sản phẩm có id '.$id],200);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $producttype = ProductTypes::find($id);
        if(count($producttype->product) === 0) {
            if($producttype->delete()){
                return response()->json(['result' => 'Đã xóa thành công loại sản phẩm có id '.$id],200);
            }else{
                return response()->json(['result' => 'Đã xóa không thành công loại sản phẩm có id '.$id],200);
            }
        } else {
            return response()->json(['result' => 'Không thể xóa loại sản phẩm khi có sản phẩm'],200);
        }
    }
}

resources/views/admin/pages/producttype/add.blade.php
@extends('admin.layouts.master')

@section('title')
    Danh sách các nhà cung cấp
@endsection

@section('content')
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary"> Danh sách nhà cung cấp</h6>
        </div>
        <div class="row" style="margin: 5px">
            <div class="col-lg-12">
                <form role="form" action="{{ route('producttype.store') }}" method="post">
                    @csrf
                    <fieldset class="form-group">
                        <label>Tên nhà cung cấp</label>
                        <input class="form-control" name="name" placeholder="Nhập tên nhà cung cấp">
                        @if($errors->has('name'))
                            <div class="alert alert-danger">{{ $errors->first('name') }}</div>
                        @endif
                    </fieldset>
                    <div class="form-group">
                        <label>Nhóm sản phẩm</label>
                        <select class="form-control" name="idCategory">
                            @foreach($category as $cate)
                                <option value="{{ $cate->id }}">{{ $cate->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Trạng thái</label>
                        <select class="form-control" name="status">
                            <option value="1">Hiển Thị</option>
                            <option value="0">Không Hiển Thị</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-success">Thêm</button>
                    <button type="reset" class="btn btn-primary">Nhập Lại</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/pages/producttype/list.blade.php
@extends('admin.layouts.master')

@section('title')
    Danh sách các nhà cung cấp
@endsection

@section('content')
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Danh sách nhà cung cấp</h6>
            <a href="{{route('producttype.create')}}" class="btn btn-success float-right"> Thêm mới  <i class="fas fa-plus"></i></a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>STT</th>
                        <th>Tên nhà cung cấp</th>
                        <th>Slug</th>
                        <th>Nhóm sản phẩm</th>
                        <th>Trạng thái</th>
                        <th>Tùy chọn</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($producttype as $key => $value)
                        <tr>
                            <td>{{ $key+1 }}</td>
                            <td>{{ $value->name }}</td>
                            <td>{{ $value->slug }}</td>
                            <td>{{ $value->Category->name }}</td>
                            <td>
                                @if($value->status == 1)
                                    <label class="label label-success">Hiển thị</label>
                                @else
                                    <label class="label label-danger">Không Hiển Thị</label>
                                @endif
                            </td>
                            <td>
                                <button class="btn btn-primary editProducttype" title="{{ "Sửa ".$value->name }}" data-toggle="modal" data-target="#edit" type="button" data-id="{{ $value->id }}"><i class="fas fa-edit"></i></button>
                                <button class="btn btn-danger deleteProducttype" title="{{ "Xóa ".$value->name }}" data-toggle="modal" data-target="#delete" type="button" data-id="{{ $value->id }}"><i class="fas fa-trash-alt"></i></button>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <div class="float-right">{{ $producttype->links() }}</div>
            </div>
        </div>
    </div>
    <!-- Edit Modal-->
    <div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Chỉnh sửa nhà cung cấp <span class="title"></span></h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row" style="margin: 5px">
                        <div class="col-lg-12">
                            <form role="form">
                                <fieldset class="form-group">
                                    <label>Tên nhà cung cấp</label>
                                    <input class="form-control name" name="name" placeholder="Nhập tên nhà cung cấp">
                                    <div class="alert alert-danger error"></div>
                                </fieldset>
                                <div class="form-group">
                                    <label>Nhóm sản phẩm</label>
                                    <select class="form-control idCategory" name="idCategory"></select>
                                </div>
                                <div class="form-group">
                                    <label>Trạng thái</label>
                                    <select class="form-control" name="status">
                                        <option value="1" class="ht">Hiển Thị</option>
                                        <option value="0" class="kht">Không Hiển Thị</option>
                                    </select>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-success updateProductType">Lưu</button>
                    <button type="reset" class="btn btn-primary">Nhập lại</button>
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Hủy bỏ</button>
                </div>
            </div>
        </div>
    </div>
    <!-- delete Modal-->
    <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Bạn có muốn xóa ?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body" style="margin-left: 183px;">
                    <button type="button" class="btn btn-success delProductType">Có</button>
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Không</button>
                    <div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection