routes/web.php
<?php
//use Illuminate\Support\Facades\Route;
//use App\Http\Controllers\HomeController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Admin
Route::post('admin/login','UserController@loginAdmin')->name('admin.login');
Route::view('admin/login','admin.pages.login')->name('login.admin');
Route::get('/logoutAdmin','UserController@logoutAdmin')->name('logoutAdmin');

Route::get('getproducttype','AjaxController@getProductType');
Route::group(['prefix' => 'admin', 'middleware' => 'adminMiddleware'],function(){
    Route::resource('dashboard','DashboardController');
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('category','CategoryController');
    Route::resource('producttype','ProductTypeController');
    Route::resource('product','ProductController');
    Route::resource('order','OrderController');
    Route::resource('warranty','WarrantyController');

    Route::get('getlist','UserController@getList')->name('user.getList');

    Route::get('deleteUser/{id}','UserController@destroy')->name('user.delete');

    Route::get('createUser','UserController@create')->name('user.create');

    Route::post('addUser','UserController@store')->name('user.add');

    Route::get('editUser/{id}','UserController@edit')->name('user.edit');

    Route::post('updateUser','UserController@update')->name('user.update');

    Route::get('updateWar/{id}','WarrantyController@update')->name('warranty.update');

    Route::get('completeWar/{id}','WarrantyController@complete')->name('warranty.complete');

    Route::get('cancelWar/{id}','WarrantyController@cancel')->name('warranty.cancel');

    Route::post('updatePro/{id}','ProductController@update');

    Route::get('cancle/{id}','OrderController@cancle')->name('order.cancle');

    Route::get('check/{id}','OrderController@check')->name('order.check');

    Route::get('complete/{id}','OrderController@complete')->name('order.complete');
});

//Client
Route::post('login','UserController@loginClient')->name('login');
Route::get('/logout','UserController@logout')->name('logout');
Route::post('register','UserController@registerClient')->name('register');
Route::get('/myorder','UserController@index')->name('myorder');
Route::get('/myorder/show/{id}','UserController@show')->name('myorder.show');
Route::get('/myorder/warranty/{id}','WarrantyController@create')->name('myorder.warranty');
Route::post('/myorder/warranty/send','WarrantyController@store')->name('warranty.send');

Route::get('/','HomeController@index')->name('home-page');
Route::get('trangchu.html','HomeController@index');
Route::resource('cart','CartController');
Route::get('addcart/{id}','CartController@addCart')->name('addCart');

Route::view('checkout','client.pages.checkout');
Route::get('checkout','CartController@checkout')->name('cart.checkout');
Route::resource('customer','CustomerController');
Route::get('/{slug}.html', 'HomeController@getDetail')->name('product-detail');

Route::post('searchname','ProductController@searchName')->name('search.name');
Route::post('searchtype','ProductController@searchType')->name('search.type');

Route::get('/warranty-period/{order_id}/{product_id}', 'WarrantyController@getPeriod');

Route::get('/danh-muc/{slug}/{id}', 'HomeController@getProductByCategory')->name('product.get-by-category');
Route::get('/danh-muc-loai/{slug}/{id}', 'HomeController@getProductByProductTypes')->name('producttype.get-by-category');

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;
use App\Models\Categories;
use App\Http\Requests\StoreCategoryRequest;
use Validator;
use Auth;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        $category=Categories::paginate(10);
        if($user->can('view',Categories::class)) {
            return view('admin.pages.category.list',compact("category"));
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = Auth::user();
        if($user->can('create',Categories::class)) {
            return view('admin.pages.category.add');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCategoryRequest $request)
    {
        $user = Auth::user();
        if ($user->can('create',Categories::class)) {
            Categories::create([
                'name' => $request->name,
                'slug' => utf8tourl($request->name),
                'status' => $request->status
            ]);
            return redirect()->route('category.index');

        }
    }


    /**
     * Display the specified resource.
     *
     * @param  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = Auth::user();
        if ($user->can('update', Categories::class)) {
            $category = Categories::find($id);
            return response()->json($category, 200);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreCategoryRequest $request, $id)
    {
        $user = Auth::user();
        if ($user->can('update', Categories::class)) {
            $category = Categories::find($id);
            $category->update(
                [
                    'name' => $request->name,
                    'slug' => utf8tourl($request->name),
                    'status' => $request->status
                ]
            );
            return response()->json(['success' => 'Sửa thành công']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
//        $user = Auth::user();
//        if ($user->can('delete', Categories::class)) {
            $category = Categories::find($id);
            if(count($category->productType) === 0) {
                $category->delete();
                return response()->json(['success' => 'Xóa thành công']);
            } else {
                return response()->json(['success' => 'Không thể xóa khi còn loại sản phẩm']);
            }
        }
//    }
}

resources/views/admin/pages/category/add.blade.php
@extends('admin.layouts.master')

@section('title')
    Thêm nhóm sản phẩm
@endsection

@section('content')
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Nhóm sản phẩm</h6>
        </div>
        <div class="row" style="margin: 5px">
            <div class="col-lg-12">
                <form role="form" action="{{ route('category.store') }}" method="post">
                    @csrf
                    <fieldset class="form-group">
                        <label>Tên nhóm sản phẩm</label>
                        <input class="form-control" name="name" placeholder="Nhập tên nhóm">
                    </fieldset>
                    <div class="form-group">
                        <label>Trạng thái</label>
                        <select class="form-control" name="status">
                            <option value="1">Hiển Thị</option>
                            <option value="0">Không Hiển Thị</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-success">Lưu</button>
                    <button type="reset" class="btn btn-primary">Nhập lại</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/pages/category/list.blade.php
@extends('admin.layouts.master')

@section('title')
    Danh sách các nhóm sản phẩm
@endsection

@section('content')
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Danh sách nhóm sản phẩm</h6>
            <a href="{{route('category.create')}}" class="btn btn-success float-right mr-3"> Thêm mới  <i class="fas fa-plus"></i></a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>STT</th>
                        <th>Tên nhóm</th>
                        <th>Slug</th>
                        <th>Trạng thái</th>
                        <th>Tùy chọn</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($category as $key => $value)
                        <tr>
                            <td>{{ $key+1 }}</td>
                            <td>{{ $value->name }}</td>
                            <td>{{ $value->slug }}</td>
                            <td>
                                @if($value->status == 1)
                                    <label class="label label-success">Hiển thị</label>
                                @else
                                    <label class="label label-danger">Không Hiển Thị</label>
                                @endif
                            </td>
                            <td>
                                <button class="btn btn-primary edit" title="{{ "Sửa ".$value->name }}" data-toggle="modal" data-target="#edit" type="button" data-id="{{ $value->id }}"><i class="fas fa-edit"></i></button>
                                <button class="btn btn-danger delete" title="{{ "Xóa ".$value->name }}" data-toggle="modal" data-target="#delete" type="button" data-id="{{ $value->id }}"><i class="fas fa-trash-alt"></i></button>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <div class="pull-right">{{ $category->links() }}</div>
            </div>
        </div>
    </div>
    <!-- Edit Modal-->
    <div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Chỉnh sửa nhóm sản phẩm <span class="title"></span></h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row" style="margin: 5px">
                        <div class="col-lg-12">
                            <form role="form">

                                <!-- <input type="hidden" name="id" value=""> -->
                                <fieldset class="form-group">
                                    <label>Tên nhóm sản phẩm</label>
                                    <input class="form-control name" name="name" placeholder="Nhập tên tên nhóm">
                                    <span class="error" style="color: red;font-size: 1rem;"></span>
                                </fieldset>
                                <div class="form-group">
                                    <label>Status</label>
                                    <select class="form-control status" name="Trạng thái">
                                        <option value="1" class="ht">Hiển Thị</option>
                                        <option value="0" class="kht">Không Hiển Thị</option>
                                    </select>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-success update">Lưu</button>
                    <button type="reset" class="btn btn-primary">Nhập Lại</button>
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Hủy bỏ</button>
                </div>
            </div>
        </div>
    </div>
    <!-- delete Modal-->
    <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Bạn có muốn xóa ?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body" style="margin-left: 183px;">
                    <button type="button" class="btn btn-success del">Có</button>
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Không</button>
                </div>
            </div>
        </div>
    </div>
@endsection