routes/web.php
<?php
//use Illuminate\Support\Facades\Route;
//use App\Http\Controllers\HomeController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Admin
Route::post('admin/login','UserController@loginAdmin')->name('admin.login');
Route::view('admin/login','admin.pages.login')->name('login.admin');
Route::get('/logoutAdmin','UserController@logoutAdmin')->name('logoutAdmin');

Route::get('getproducttype','AjaxController@getProductType');
Route::group(['prefix' => 'admin', 'middleware' => 'adminMiddleware'],function(){
    Route::resource('dashboard','DashboardController');
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('category','CategoryController');
    Route::resource('producttype','ProductTypeController');
    Route::resource('product','ProductController');
    Route::resource('order','OrderController');
    Route::resource('warranty','WarrantyController');

    Route::get('getlist','UserController@getList')->name('user.getList');

    Route::get('deleteUser/{id}','UserController@destroy')->name('user.delete');

    Route::get('createUser','UserController@create')->name('user.create');

    Route::post('addUser','UserController@store')->name('user.add');

    Route::get('editUser/{id}','UserController@edit')->name('user.edit');

    Route::post('updateUser','UserController@update')->name('user.update');

    Route::get('updateWar/{id}','WarrantyController@update')->name('warranty.update');

    Route::get('completeWar/{id}','WarrantyController@complete')->name('warranty.complete');

    Route::get('cancelWar/{id}','WarrantyController@cancel')->name('warranty.cancel');

    Route::post('updatePro/{id}','ProductController@update');

    Route::get('cancle/{id}','OrderController@cancle')->name('order.cancle');

    Route::get('check/{id}','OrderController@check')->name('order.check');

    Route::get('complete/{id}','OrderController@complete')->name('order.complete');
});

//Client
Route::post('login','UserController@loginClient')->name('login');
Route::get('/logout','UserController@logout')->name('logout');
Route::post('register','UserController@registerClient')->name('register');
Route::get('/myorder','UserController@index')->name('myorder');
Route::get('/myorder/show/{id}','UserController@show')->name('myorder.show');
Route::get('/myorder/warranty/{id}','WarrantyController@create')->name('myorder.warranty');
Route::post('/myorder/warranty/send','WarrantyController@store')->name('warranty.send');

Route::get('/','HomeController@index')->name('home-page');
Route::get('trangchu.html','HomeController@index');
Route::resource('cart','CartController');
Route::get('addcart/{id}','CartController@addCart')->name('addCart');

Route::view('checkout','client.pages.checkout');
Route::get('checkout','CartController@checkout')->name('cart.checkout');
Route::resource('customer','CustomerController');
Route::get('/{slug}.html', 'HomeController@getDetail')->name('product-detail');

Route::post('searchname','ProductController@searchName')->name('search.name');
Route::post('searchtype','ProductController@searchType')->name('search.type');

Route::get('/warranty-period/{order_id}/{product_id}', 'WarrantyController@getPeriod');

Route::get('/danh-muc/{slug}/{id}', 'HomeController@getProductByCategory')->name('product.get-by-category');
Route::get('/danh-muc-loai/{slug}/{id}', 'HomeController@getProductByProductTypes')->name('producttype.get-by-category');

resources/views/admin/layouts/footer.blade.php
<!-- Footer -->
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; AUTO 368 - Nam Anh Design</span>
        </div>
    </div>
</footer>
<!-- End of Footer -->

</div>
<!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Bạn chắc chắn muốn đăng xuất?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Chọn nút đăng xuất bên dưới nếu bạn đã sẵn sàng kết thúc phiên làm việc của mình.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Hủy</button>
                <a class="btn btn-success" href="{{ route('logoutAdmin') }}">Đăng xuất</a>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript-->
<script src="assets/admin/vendor/jquery/jquery.min.js"></script>
<script src="assets/admin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="https://printjs-4de6.kxcdn.com/print.min.js"></script>

<script src="{{ asset('plugins/jquery.dataTables.min.js') }}"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script> 
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.html5.min.js"></script>
<!-- Core plugin JavaScript-->
<script src="assets/admin/vendor/jquery-easing/jquery.easing.min.js"></script>
<script type="text/javascript" src="{{ asset('plugins/moment/moment.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('plugins/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
@stack('js')
<!-- Custom scripts for all pages-->
<script src="assets/admin/js/sb-admin-2.min.js"></script>
<script src="assets/admin/js/ajax.js"></script>
<script src="assets/admin/js/toastr.min.js"></script>
<script type="text/javascript" src="ckeditor/ckeditor.js"></script>
<script type="text/javascript">
    CKEDITOR.replace( 'demo' );
</script>

@if(session('thongbao'))
    <script type="text/javascript">
        toastr.success('{{ session('thongbao') }}', 'Thông báo', {timeOut: 5000});
    </script>
@endif
@if(session('error'))
    <script type="text/javascript">
        toastr.error('{{ session('error') }}', 'Thông báo', {timeOut: 5000});
    </script>
@endif
<!-- Google chart-->
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
{{-- <script type="text/javascript">
    var arr = [['Ngày', 'Tổng tiền']];
    var orders = JSON.parse(document.getElementById("order").value);
    google.charts.load('current', {'packages':['corechart']});
    google.charts.setOnLoadCallback(drawChart);
    for(x of orders){
      arr.push([x.date,parseInt(x.total_price)])
    } 
    function drawChart() {

      var data = google.visualization.arrayToDataTable(arr);

      var options = {
        title: 'Thống kê doanh thu theo ngày'
      };

      var chart = new google.visualization.PieChart(document.getElementById('piechart'));

      chart.draw(data, options);
    }

    var option = [['Ngày', 'Tổng số đơn hàng']];
    var counts = JSON.parse(document.getElementById("count").value);
    google.charts.load('current', {'packages':['corechart']});
    google.charts.setOnLoadCallback(drawCountChart);
    for(x of counts){
      option.push([x.date,parseInt(x.count_order)])
    } 
    function drawCountChart() {

      var data = google.visualization.arrayToDataTable(option);

      var options = {
        title: 'Thống kê tổng số đơn hàng hoàn thành theo ngày'
      };

      var chart = new google.visualization.PieChart(document.getElementById('orderchart'));

      chart.draw(data, options);
    }
</script> --}}

resources/views/admin/layouts/header.blade.php
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>
    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>
        <!-- Nav Item - Alerts -->

        <div class="topbar-divider d-none d-sm-block"></div>
        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-dark small" style="font-size:18px;">{{ Auth::user()->name }}</span>
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <!-- <a class="dropdown-item" href="#">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i> Profile
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i> Settings
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i> Activity Log
                </a>
                <div class="dropdown-divider"></div> -->
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i> Đăng xuất
                </a>
            </div>
        </li>
    </ul>
</nav>

resources/views/admin/layouts/master.blade.php
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ asset('') }}">
    <title>@yield('title')</title>
    <!-- Custom fonts for this template-->
    <link href="assets/admin/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="assets/admin/css/nunito.css" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="assets/admin/css/sb-admin-2.min.css" rel="stylesheet">
    <link rel="stylesheet" href="assets/admin/css/toastr.css">
    <link rel="stylesheet" href="https://printjs-4de6.kxcdn.com/print.min.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('plugins/bootstrap-daterangepicker/daterangepicker.css') }}" />
    <link rel="stylesheet" href="{{ asset('css/common.css') }}">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.4.1/css/buttons.dataTables.min.css">
</head>
<body id="page-top">
<!-- Page Wrapper -->
<div id="wrapper">
    <!-- Sidebar -->
@include('admin.layouts.menu')
<!-- End of Sidebar -->
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">
        <!-- Main Content -->
        <div id="content">
            <!-- Topbar -->
        @include('admin.layouts.header')
        <!-- End of Topbar -->
            <!-- Begin Page Content -->
            <div class="container-fluid">
                @yield('content')
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- End of Main Content -->
    </div>
</div>
@include('admin.layouts.footer')
</body>
</html>

resources/views/admin/layouts/menu.blade.php
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-car"></i>
        </div>
        <div class="sidebar-brand-text mx-3">AUTO 368</div>
    </a>
    <!-- Divider -->
    @if(Auth::user()->role == 1)
    <hr class="sidebar-divider my-0">
    <!-- Nav Item - Dashboard -->
    <li class="nav-item">
        <a class="nav-link" href="{{ route('dashboard.index') }}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Thống Kê</span>
        </a>
    </li>
    @endif
    @if(Auth::user()->role == 1)
    <!-- Divider -->
        <hr class="sidebar-divider">
        <!-- Heading -->
        <div class="sidebar-heading">
            Thành viên hệ thống
        </div>
        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUser" aria-expanded="true" aria-controls="collapseTwo">
                <i class="fas fa-users"></i>
                <span>Thành viên</span>
            </a>
            <div id="collapseUser" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Thành viên</h6>
                    <a class="collapse-item" href="{{ route('user.getList') }}">Danh sách</a>
                        <a class="collapse-item" href="{{ route('user.create') }}">Thêm mới</a>
                </div>
            </div>
        </li>
    @endif
    @if(Auth::user()->role == 1 || Auth::user()->role == 2)
        <!-- Divider -->
        <hr class="sidebar-divider">
        <!-- Heading -->
        <div class="sidebar-heading">
            Quản lý sản phẩm
        </div>
        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                <i class="fas fa-fw fa-cog"></i>
                <span>Nhóm sản phẩm</span>
            </a>
            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Nhóm sảm phẩm</h6>
                    <a class="collapse-item" href="{{ route('category.index') }}">Danh sách</a>
                    <a class="collapse-item" href="{{ route('category.create') }}">Thêm mới</a>
                </div>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#producttype" aria-expanded="true" aria-controls="collapseTwo">
                <i class="fas fa-fw fa-cog"></i>
                <span> Nhà cung cấp</span>
            </a>
            <div id="producttype" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header"> Nhà cung cấp</h6>
                    <a class="collapse-item" href="{{ route('producttype.index') }}">Danh sách</a>
                    <a class="collapse-item" href="{{ route('producttype.create') }}">Thêm mới</a>
                </div>
            </div>
        </li>
    @endif
    @if(Auth::user()->role == 1 || Auth::user()->role == 2)
        <hr class="sidebar-divider">
        <!-- Heading -->
        <div class="sidebar-heading">
            Sản phẩm
        </div>
        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#product" aria-expanded="true" aria-controls="collapseTwo">
                <i class="fas fa-fw fa-cog"></i>
                <span>Sản phẩm</span>
            </a>
            <div id="product" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Quản Lý Sảm Phẩm</h6>
                    <a class="collapse-item" href="{{ route('product.index') }}">Danh sách</a>
                    <a class="collapse-item" href="{{ route('product.create') }}">Thêm mới</a>
                </div>
            </div>
        </li>

        <hr class="sidebar-divider">
        <!-- Heading -->
        <div class="sidebar-heading">
            Đơn hàng
        </div>
        <!-- Nav Item - Dashboard -->
        <li class="nav-item">
            <a class="nav-link" href="{{ route('order.index') }}">
                <i class="far fa-money-bill-alt"></i>
                <span>Đơn đặt hàng</span>
            </a>
        </li>
        <hr class="sidebar-divider">
        @endif
        @if(Auth::user()->role == 1 || Auth::user()->role == 3)
        <!-- Heading -->
        <div class="sidebar-heading">
            Đơn bảo hành
        </div>
        <li class="nav-item">
            <a class="nav-link" href="{{ route('warranty.index') }}">
                <i class="fas fa-tools"></i>
                <span>Đơn bảo hành</span>
            </a>
        </li>
        @endif
</ul>