routes/web.php
<?php
//use Illuminate\Support\Facades\Route;
//use App\Http\Controllers\HomeController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Admin
Route::post('admin/login','UserController@loginAdmin')->name('admin.login');
Route::view('admin/login','admin.pages.login')->name('login.admin');
Route::get('/logoutAdmin','UserController@logoutAdmin')->name('logoutAdmin');

Route::get('getproducttype','AjaxController@getProductType');
Route::group(['prefix' => 'admin', 'middleware' => 'adminMiddleware'],function(){
    Route::resource('dashboard','DashboardController');
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('category','CategoryController');
    Route::resource('producttype','ProductTypeController');
    Route::resource('product','ProductController');
    Route::resource('order','OrderController');
    Route::resource('warranty','WarrantyController');

    Route::get('getlist','UserController@getList')->name('user.getList');

    Route::get('deleteUser/{id}','UserController@destroy')->name('user.delete');

    Route::get('createUser','UserController@create')->name('user.create');

    Route::post('addUser','UserController@store')->name('user.add');

    Route::get('editUser/{id}','UserController@edit')->name('user.edit');

    Route::post('updateUser','UserController@update')->name('user.update');

    Route::get('updateWar/{id}','WarrantyController@update')->name('warranty.update');

    Route::get('completeWar/{id}','WarrantyController@complete')->name('warranty.complete');

    Route::get('cancelWar/{id}','WarrantyController@cancel')->name('warranty.cancel');

    Route::post('updatePro/{id}','ProductController@update');

    Route::get('cancle/{id}','OrderController@cancle')->name('order.cancle');

    Route::get('check/{id}','OrderController@check')->name('order.check');

    Route::get('complete/{id}','OrderController@complete')->name('order.complete');
});

//Client
Route::post('login','UserController@loginClient')->name('login');
Route::get('/logout','UserController@logout')->name('logout');
Route::post('register','UserController@registerClient')->name('register');
Route::get('/myorder','UserController@index')->name('myorder');
Route::get('/myorder/show/{id}','UserController@show')->name('myorder.show');
Route::get('/myorder/warranty/{id}','WarrantyController@create')->name('myorder.warranty');
Route::post('/myorder/warranty/send','WarrantyController@store')->name('warranty.send');

Route::get('/','HomeController@index')->name('home-page');
Route::get('trangchu.html','HomeController@index');
Route::resource('cart','CartController');
Route::get('addcart/{id}','CartController@addCart')->name('addCart');

Route::view('checkout','client.pages.checkout');
Route::get('checkout','CartController@checkout')->name('cart.checkout');
Route::resource('customer','CustomerController');
Route::get('/{slug}.html', 'HomeController@getDetail')->name('product-detail');

Route::post('searchname','ProductController@searchName')->name('search.name');
Route::post('searchtype','ProductController@searchType')->name('search.type');

Route::get('/warranty-period/{order_id}/{product_id}', 'WarrantyController@getPeriod');

Route::get('/danh-muc/{slug}/{id}', 'HomeController@getProductByCategory')->name('product.get-by-category');
Route::get('/danh-muc-loai/{slug}/{id}', 'HomeController@getProductByProductTypes')->name('producttype.get-by-category');

resources/views/client/layouts/footer.blade.php
<footer id="contact">
    <div class="footer-top-first">
        <div class="container py-md-5 py-sm-4 py-3">
            <!-- footer first section -->
            <h2 class="footer-top-head-w3l font-weight-bold mb-2">AUTO 368 :</h2>
            <p class="footer-main mb-4">
               Sự hài lòng của quý khách hàng là niềm vui và là thành công lớn nhất của công ty chúng tôi.!</p>
            <!-- //footer first section -->
            <!-- footer second section -->
            <div class="row w3l-grids-footer border-top border-bottom py-sm-4 py-3">
                <div class="col-md-4 offer-footer">
                    <div class="row">
                        <div class="col-4 icon-fot">
                            <i class="fas fa-dolly"></i>
                        </div>
                        <div class="col-8 text-form-footer">
                            <h3>Chất lượng phục vụ tốt nhất </h3>
                            <p>Khách hàng sẽ được đáp ứng mọi mong muốn của mình với sản phẩm</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 offer-footer my-md-0 my-4">
                    <div class="row">
                        <div class="col-4 icon-fot">
                            <i class="fas fa-shipping-fast"></i>
                        </div>
                        <div class="col-8 text-form-footer">
                            <h3>Giao hàng nhanh chóng</h3>
                            <p>Toàn quốc</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 offer-footer">
                    <div class="row">
                        <div class="col-4 icon-fot">
                            <i class="far fa-thumbs-up"></i>
                        </div>
                        <div class="col-8 text-form-footer">
                            <h3>Uy tín của chúng tôi</h3>
                            <p>Sự lựa chọn đúng đắn của bạn.!</p>
                        </div>
                    </div>
                </div>
            </div>
            <!-- //footer second section -->
        </div>
    </div>
    <!-- footer third section -->
    <div class="w3l-middlefooter-sec">
        <div class="container py-md-5 py-sm-4 py-3">
            <div class="row footer-info w3-agileits-info">
                <div class="col-md-3 col-sm-6 footer-grids mt-md-0 mt-4">
                    <h3 class="text-white font-weight-bold mb-3">Liên hệ với chúng tôi</h3>
                    <ul>
                        <li class="mb-3">
                            <i class="fas fa-map-marker"></i> 79 Dương Đình Nghệ - Cầu Giấy - HN</li>
                        <li class="mb-3">
                            <i class="fas fa-mobile"></i> 024 8888 99999 </li>
                        <li class="mb-3">
                            <i class="fas fa-phone"></i> 09 8888 9999 </li>
                        <li class="mb-3">
                            <i class="fas fa-envelope-open"></i>
                            <a href="mailto:example@mail.com"> auto368@gmail.com</a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-6 footer-grids w3l-agileits mt-md-0 mt-4">
                    <!-- newsletter -->
                    <h3 class="text-white font-weight-bold mb-3">Những tin tức mới nhất</h3>
                    <p class="mb-3">Cập nhật thường xuyên về các sản phẩm mới</p>
                    <form action="#" method="post">
                        <div class="form-group">
                            <input type="email" class="form-control" placeholder="Email" name="email" required="">
                            <input type="submit" value="Nhập">
                        </div>
                    </form>
                    <!-- //newsletter -->
                    <!-- social icons -->
                    <div class="footer-grids  w3l-socialmk mt-3">
                        <h3 class="text-white font-weight-bold mb-3">Theo dõi </h3>
                        <div class="social">
                            <ul>
                                <li>
                                    <a class="icon fb" href="#">
                                        <i class="fab fa-facebook-f"></i>
                                    </a>
                                </li>
                                <li>
                                    <a class="icon tw" href="#">
                                        <i class="fab fa-twitter"></i>
                                    </a>
                                </li>
                                <li>
                                    <a class="icon gp" href="#">
                                        <i class="fab fa-google-plus-g"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- //social icons -->
                </div>
            </div>
            <!-- //quick links -->
        </div>
    </div>
    <!-- //footer third section -->
</footer>
<div class="copy-right py-3">
    <div class="container">
        <p class="text-center text-white">© 2021 AUTO 368 All rights reserved | Design by
            <a href="/"> Nam Anh</a>
        </p>
    </div>
</div>
<script src="{{ asset('assets/client/js/jquery-2.2.3.min.js') }}"></script>
<script src="{{ asset('assets/client/js/jquery.magnific-popup.js') }}"></script>
<script src="{{ asset('assets/client/js/minicart.js') }}"></script>
<!-- //cart-js -->
<!-- scroll seller -->
<script src="{{ asset('assets/client/js/scroll.js') }}"></script>
<!-- //scroll seller -->
<!-- smoothscroll -->
{{-- <script src="{{ asset('assets/client/js/SmoothScroll.min.js') }}"></script> --}}
<!-- //smoothscroll -->
<!-- start-smooth-scrolling -->
<script src="{{ asset('assets/client/js/move-top.js') }}"></script>
<script src="{{ asset('assets/client/js/easing.js') }}"></script>
<!-- for bootstrap working -->
<script src="{{ asset('assets/client/js/bootstrap.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/client/js/custom.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/client/js/toastr.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/client/js/ajax.js') }}"></script>

<!-- imagezoom -->
<script src="{{ asset('assets/client/js/imagezoom.js') }}"></script>
<!-- //imagezoom -->
<!-- flexslider -->
<link rel="stylesheet" href="{{ asset('assets/client/css/flexslider.css') }}" type="text/css" media="screen" />

<script src="{{ asset('assets/client/js/jquery.flexslider.js') }}"></script>
<script>
    // Can also be used with $(document).ready()
    $(window).load(function () {
        $('.flexslider').flexslider({
            animation: "slide",
            controlNav: "thumbnails"
        });
    });
</script>
<!-- //FlexSlider-->
<!-- smoothscroll -->
<script src="{{ asset('assets/client/js/SmoothScroll.min.js') }}"></script>
<!-- //smoothscroll -->
@if( isset($user) && count($user->customer) == 0 )
    <script>
        $('#address').modal('show');
    </script>
@endif

resources/views/client/layouts/header-bottom.blade.php
<div class="header-bot">
    <div class="container">
        <div class="row header-bot_inner_wthreeinfo_header_mid">
            <!-- logo -->
            <div class="col-md-3 logo_agile">
                <a href="/">
                    <img src="{{ asset('assets/client/images/logo2.png') }}" alt="" width=150>
                </a>
            </div>
            <!-- //logo -->
            <!-- header-bot -->
            <div class="col-md-9 header mt-4 mb-md-0 mb-4">
                <div class="row">
                    <!-- search -->
                    <div class="col-10 agileits_search">
                        <form class="form-inline" action="{{ route('search.name') }}" method="post">
                            @csrf
                            <input class="form-control mr-sm-2" name="q" type="search" placeholder="Nhập tên sản phẩm mà bạn muốn tìm kiếm" aria-label="Search" required>
                            <button class="btn my-2 my-sm-0" type="submit">Tìm kiếm</button>
                        </form>
                    </div>
                    <!-- //search -->
                    <!-- cart details -->
                    <div class="col-2 top_nav_right text-center mt-sm-0 mt-2">
                        <div class="wthreecartaits wthreecartaits2 cart cart box_1" >
                                <a @if(Auth::check())  href=" {{ route('cart.index') }} " @else data-toggle="modal" data-target="#login" href="#"
                                   @endif title="Bạn đã chọn  {{ Cart::count() }} mặt hàng" class="btn w3view-cart">
                                    <i class="fas fa-cart-arrow-down"></i>
                                </a>
                        </div>
                    </div>
                    <!-- //cart details -->
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/client/layouts/header-top.blade.php
<div class="agile-main-top">
    <div class="container-fluid">
        <div class="row main-top-w3l py-2">
            <div class="col-lg-6 header-most-top">
                <p class="text-white text-lg-left text-center">79 Dương Đình Nghệ - Cầu Giấy - Hà Nội
                    <i class="fas fa-phone mr-2"></i> 0989 888 999
                </p>
            </div>
            <div class="col-lg-6 header-right mt-lg-0 mt-2">
                <!-- header lists -->
                <ul>
                    @if(Auth::check())
                    <li class="text-center border-right text-white">
                        <a href="{{ route('myorder') }}" class="text-white">
                            <i class="fas fa-truck mr-2"></i>Xem các đơn hàng</a>
                    </li>
                    @endif
                    @if(Auth::check())
                        <li class="text-center border-right text-white">
                                <a href="{{ route('logout') }}" style="color: #ff4d4d;">
                                    <i class="fas fa-sign-in-alt mr-2"></i>
                                </a>
                                {{ Auth::user()->name }}
                        </li>
                    @else
                    <li class="text-center border-right text-white">
                        <a href="#" data-toggle="modal" data-target="#login" class="text-white">
                            <i class="fas fa-sign-in-alt mr-2"></i> Đăng Nhập </a>
                    </li>
                    <li class="text-center text-white">
                        <a href="#" data-toggle="modal" data-target="#register" class="text-white">
                            <i class="fas fa-sign-out-alt mr-2"></i>Đăng ký </a>
                    </li>
                    @endif
                </ul>
                <!-- //header lists -->
            </div>
        </div>
    </div>
</div>

resources/views/client/layouts/master.blade.php

<!DOCTYPE html>
<html lang="vi">
<head>
    <title> AUTO 368 - @yield('title') </title>
    <!-- Meta tag Keywords -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8" />
    <meta name="keywords" content="Electro Store Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design"/>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!-- //Meta tag Keywords -->
    <!-- Custom-Files -->
    <link href="{{ asset('assets/client/css/bootstrap.css') }}" rel="stylesheet" type="text/css" media="all" />
    <!-- Bootstrap css -->
    <link href="{{ asset('assets/client/css/style.css') }}" rel="stylesheet" type="text/css" media="all" />
    <!-- Main css -->
    <link href="{{ asset('assets/admin/vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
    <!-- Font-Awesome-Icons-CSS -->
    <link href="{{ asset('assets/client/css/popuo-box.css') }}" rel="stylesheet" type="text/css" media="all" />
    <!-- pop-up-box -->
    <link href="{{ asset('assets/client/css/menu.css') }}" rel="stylesheet" type="text/css" media="all" />
    <!-- menu style -->
    <!-- //Custom-Files -->
    <!-- web fonts -->
    <link href="{{ asset('assets/client/css/lato.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/client/css/opensan.css') }}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/admin/js/toastr.min.js') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/client/css/easy-responsive-tabs.css') }}">
    <link rel="stylesheet" href="{{ asset('css/common.css') }}">

    <!-- //web fonts -->
</head>
<body>
 @include('client.layouts.header-top')
<!-- top-header -->
<!-- modals -->
<!-- log in -->
<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-center">Đăng Nhập</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{{ route('login') }}" method="post">
                    @csrf
                    <div class="form-group">
                        <label class="col-form-label">Tên đăng nhập</label>
                        <input type="text" class="form-control" placeholder="Tên đăng nhập " name="name">
                    </div>
                    <div class="form-group">
                        <label class="col-form-label">Mật khẩu</label>
                        <input type="password" class="form-control" placeholder="Mật khẩu " name="Password" required="">
                    </div>
                    <div class="right-w3l">
                        <input type="submit" class="form-control" value="Đăng Nhập">
                    </div>
                    <div class="sub-w3l">
                        <div class="custom-control custom-checkbox mr-sm-2">
                            <input type="checkbox" class="custom-control-input" id="customControlAutosizing" name="remember">
                            <label class="custom-control-label" for="customControlAutosizing">Lưu thông tin đăng nhập</label>
                        </div>
                    </div>
                    <p class="text-center dont-do mt-3">Bạn chưa có tài khoản?
                        <a href="#" data-toggle="modal" data-target="#register">
                            Đăng ký ngay</a>
                    </p>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- register -->
<div class="modal fade" id="register" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Đăng ký</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{{ route('register') }}" method="post">
                    @csrf
                    <div class="form-group">
                        <label class="col-form-label">Họ và tên</label>
                        <input type="text" class="form-control" placeholder="Nhập họ và tên " name="name" required="">
                        @if($errors->has('name'))
                            <div class="alert alert-danger">
                                {{$errors->first('name') }}
                            </div>
                        @endif
                    </div>
                    <div class="form-group">
                        <label class="col-form-label">Email</label>
                        <input type="email" class="form-control" placeholder=" Nhập Email" name="email" required="">
                        @if($errors->has('email'))
                            <div class="alert alert-danger">
                                {{$errors->first('email') }}
                            </div>
                        @endif
                    </div>
                    <div class="form-group">
                        <label class="col-form-label">Mật khẩu</label>
                        <input type="password" class="form-control" placeholder="Nhập mật khẩu " name="password" id="password1" required="">
                        @if($errors->has('password'))
                            <div class="alert alert-danger">
                                {{$errors->first('password') }}
                            </div>
                        @endif
                    </div>
                    <div class="form-group">
                        <label class="col-form-label">Nhập lại mật khẩu</label>
                        <input type="password" class="form-control" placeholder="Nhập lại mật khẩu " name="re_password" id="password2" required="">
                        @if($errors->has('re_password'))
                            <div class="alert alert-danger">
                                {{$errors->first('re_password') }}
                            </div>
                        @endif
                    </div>
                    <div class="right-w3l">
                        <input type="submit" class="form-control" value="Đăng ký">
                    </div>
                    <div class="sub-w3l">
                        <div class="custom-control custom-checkbox mr-sm-2">
                            <input type="checkbox" class="custom-control-input" id="customControlAutosizing2">
                            <label class="custom-control-label" for="customControlAutosizing2">Đồng ý với điều khoản của chúng tôi</label>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- //modal -->
<!-- //top-header -->
<!-- header-bottom-->
 @include('client.layouts.header-bottom')
<!-- shop locator (popup) -->
<!-- //header-bottom -->
<!-- navigation -->
@include('client.layouts.menu')
<!-- //navigation -->
<!-- banner -->
@yield('client.layouts.slide')
<!-- //banner -->
<!-- top Products -->
@yield('slider')
<div class="ads-grid py-sm-5 py-4">
    <div class="container py-xl-4 py-lg-2">
        @yield('content')
    </div>
</div>
<!-- //top products -->
<!-- footer -->
@include('client.layouts.footer')
</body>
</html>

resources/views/client/layouts/menu.blade.php
<div class="navbar-inner sticky-menu" rel="">
	<div class="container">
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
					aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav text-center mr-xl-5">
					<li class="nav-item active mr-lg-2 mb-lg-0 mb-2">
						<a class="nav-link" href="/">Trang Chủ
							<span class="sr-only">(current)</span>
						</a>
					</li>
					@foreach($category as $cate)
						<li class="nav-item dropdown mr-lg-2 mb-lg-0 mb-2">
							<a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								{{ $cate->name }}
							</a>
							@if (count($cate->productType)>0)
									<div class="dropdown-menu">
										@foreach($cate->productType as $protype)
											<a class="dropdown-item" href="{{ route('producttype.get-by-category', [
                            'slug' => $protype->slug,
                            'id' => $protype->id
                        ]) }}">{{ $protype->name }}</a>
										@endforeach
										{{--<div class="dropdown-divider"></div>--}}
									</div>
							@endif
						</li>
					@endforeach
					<li class="nav-item">
						<a class="nav-link" href="#contact">Liên hệ</a>
					</li>
				</ul>
			</div>
            @if (Session::has('thongbao'))
                <div class="alert alert-success alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ Session::get('thongbao') }}
                </div>
            @elseif (Session::has('error'))
                <div class="alert alert-danger">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ Session::get('error') }}
                </div>
            @endif
		</nav>
	</div>
</div>

resources/views/client/layouts/sidebar.blade.php
<div class="col-lg-3 mt-lg-0 mt-4 p-lg-0 sidebar">
    <div class="side-bar p-sm-4 p-3">
        <div class="search-hotel border-bottom py-2">
            <h3 class="agileits-sear-head mb-3">Tìm kiếm nhà sản xuất</h3>
            <form action="{{ route('search.type') }}" method="post" style="display: flex">
                @csrf
                <input type="search" placeholder="Nhập tên nhà sản xuất" name="q" required>
                <input type="submit" value=" ">
            </form>
        </div>
        <!-- reviews -->
        <div class="customer-rev border-bottom left-side py-2">
            <h3 class="agileits-sear-head mb-3">Đánh giá của khách hàng</h3>
            <ul>
                <li>
                    <a href="#">
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <span>5.0</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <span>4.0</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star-half"></i>
                        <span>3.5</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <span>3.0</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star-half"></i>
                        <span>2.5</span>
                    </a>
                </li>
            </ul>
        </div>
        <!-- //reviews -->
        <!-- electronics -->
        <div class="left-side border-bottom py-2">
            <h3 class="agileits-sear-head mb-3">Các danh mục sản phẩm</h3>
            <ul>
                @foreach ($category as $item)
                    <li>
                        <a class="span" href="{{ route('product.get-by-category', [
                            'slug' => $item->slug,
                            'id' => $item->id
                        ]) }}"
                            style="font-size: 15px"
                        >{{ $item->name }}</a>
                    </li>
                @endforeach
            </ul>
        </div>
        <!-- //electronics -->
        <!-- delivery -->
        <div class="left-side border-bottom py-2">
            <h3 class="agileits-sear-head mb-3">Chính sách đổi trả hàng</h3>
            <ul>
                <li>
                    <span class="span">Đổi trả hàng trong vòng 7 ngày với các lỗi đến từ nhà sản xuất</span>
                </li>
            </ul>
        </div>
        <!-- //delivery -->
    </div>
    <!-- //product right -->
</div>